name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install all dependencies
        run: npm install

      - name: Build all packages
        run: npm run build

      - name: Run lint on all packages
        run: npm run lint

      - name: Run all tests
        run: npm run test
